# Generated by Django 4.1.4 on 2022-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_data_added_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
