# Generated by Django 4.1.4 on 2022-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_data_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
